---
title: "集合"
bibliography: 
    - ../../assets/2023.bib
    - ../../assets/2024.bib
    - ../../assets/2025.bib
csl: ../../assets/apalike.csl
---

{{< include ../../assets/_preamble.qmd >}}

* **空集合** を 
$$
\emptyset:=\{x\mid x\ne x\}
$$
で表す．^[[@Shoenfield1967 p.243], [@新井敏康2011 p.2] の定め方に一致する．]

* 集合 $X$ の [**冪集合**](https://ja.wikipedia.org/wiki/%E5%86%AA%E9%9B%86%E5%90%88) を $P(X)$ で表す．^[[@斎藤毅-位相 p.13] の記法に一致する．この定義と存在は公理から直ちに従う [nLab](https://ncatlab.org/nlab/show/power+set#foundational_status)．このときの $P$ も関手である．関手が，対象 $S$ に作用していると読めるように設計された記法である [nLab](https://ncatlab.org/nlab/show/Set#OppositeCategory)．]

* $A,B\subset X$ の [**差**](https://ja.wikipedia.org/wiki/%E5%B7%AE%E9%9B%86%E5%90%88) を
$$
A\setminus B:=\Brace{a\in A\mid a\notin B}
$$
で表す．

* 全体集合 $X$ が明白であるとき，補集合を $A^\comp:=X\setminus A$ とも表す．

* [**非交和**](https://ja.wikipedia.org/wiki/%E9%9D%9E%E4%BA%A4%E5%92%8C) $A\sqcup B$ とは，$A\cup B$ と同じ数学的対象であるが，同時に $A\cap B$ という事実も主張するものとする．^[[@斎藤毅-位相 p.10] は $A\coprod B$ と表す．[@伊藤清三63-Lebesgue積分] は $A+B$ と表す．]

* [**対称差**](https://ja.wikipedia.org/wiki/%E5%AF%BE%E7%A7%B0%E5%B7%AE) を
$$
A\triangle B:=(A\setminus B)\sqcup(B\setminus A)
$$
で表す．^[[@Dellacherie-Meyer1978] に一致．]

* 有限集合 $X$ の元の数を $\abs{X}$ または $\#X$ で表す．^[有限集合については $\Card(X)$ とも混用される，[@Gerber+2019] など．] 即ち，$\#:P(X)\to[0,\infty]$ を [計数測度](https://ja.wikipedia.org/wiki/%E6%95%B0%E3%81%88%E4%B8%8A%E3%81%92%E6%B8%AC%E5%BA%A6) とする．

* $X$ の部分集合 $A$ が有限であることを $A\fsub X$ とも略記する．

* 特に全体集合 $\Om$ が確率空間をなすとき，条件 $P$ を満たすという [**事象**](https://ja.wikipedia.org/wiki/%E4%BA%8B%E8%B1%A1_(%E7%A2%BA%E7%8E%87%E8%AB%96))
$$
A:=\Brace{\om\in\Om\mid P(\om)}
$$
を $\Brace{P}$ とも表す．^[[@Dellacherie-Meyer1978] に倣った．一般に測度論において $\Brace{f<c}:=\Brace{x\in X\mid f(x)<c}$ などのように略記される．このような集合 $A$ の存在自体は分出公理により導かれ，分出公理は通常ZF公理系の置換公理から導かれる [@新井敏康2011 p.119]．通常 $\Brace{\om\mid P(\om)}$ によって定義される数学的対象をクラスと呼び，集合を定めるとは限らないとして区別される：[ラッセルの逆理](https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%83%E3%82%BB%E3%83%AB%E3%81%AE%E3%83%91%E3%83%A9%E3%83%89%E3%83%83%E3%82%AF%E3%82%B9) が例を与える [@新井敏康2011 p.117]．]

* 例えば，$X\in\L(\Om)$ を実確率変数，$A\in\B(\R)$ を Borel 集合とすると，
$$
\Brace{X\in A}=\Brace{\om\in\Om\mid X(\om)\in A}
$$
という略記を用いる．
