---
title: "可測空間"
bibliography: 
    - ../../assets/2023.bib
    - ../../assets/2024.bib
    - ../../assets/2025.bib
csl: ../../assets/apalike.csl
---

{{< include ../../assets/_preamble.qmd >}}

* 集合族 $\cA\subset P(X)$ が生成する $\sigma$-代数を $\sigma(\cA)$ で表す．^[[@Billingsley1999] は $\sigma[\cA]$ や $\sigma[\pi_t:t\in T]$ とも表す．]

* 集合の族 $\cA\subset P(X)$ 上の関数 $\mu:\cA\to[0,\infty]$ に対して，
$$
\begin{align*}
    \mu^*(A)&:=\inf\biggl\{\sum_{n=1}^\infty\mu(A_n)\in[0,\infty]\:\bigg|\\
    &\qquad\qquad\{A_n\}\subset\A,A\subset\bigcup_{n=1}^\infty A_n\biggr\}
\end{align*}
$$
を [**外測度**](https://ja.wikipedia.org/wiki/%E5%A4%96%E6%B8%AC%E5%BA%A6) という．^[[@Bogachev2007 p.17] 定義1.5.1, [@Dudley2002 p.89] に倣った．[@vanderVaart-Wellner2023 p.6] では **外確率** という．]

* 測度空間 $(X,\A,\mu)$ において，$\A$ の $\mu$ による [**Lebesgue 完備化**](https://ja.wikipedia.org/wiki/%E5%AE%8C%E5%82%99%E6%B8%AC%E5%BA%A6) を
$$
\cA_\mu:=\Brace{A\in P(X)\:\middle|\:\substack{\forall_{\ep>0}\;\exists_{A_\ep\in\A}\\\mu^*(A\triangle A_\ep)<\ep}}
$$
で表し，この元を **$\mu$-可測集合** という．^[[@Bogachev2007 p.17] 定義1.5.1, [@Bogachev2020 p.64] に倣った．この $\cA_\mu$ は $\cA\lor\cN(\mu)$ と $\L_\mu:=\Brace{A\subset X\mid\exists_{A_1,A_2\in\cA}\;A_1\subset A\subset A}$ に一致する上，$\mu$ が $\sigma$-有限ならば $\fM_{\mu^*}:=\Brace{A\subset X\:\middle|\:\substack{\forall_{A_0\subset X}\;\mu^*(A\cap A_0)+\\\mu^*(A_0\setminus A)=\mu^*(A_0)}}$ にも一致する [@Bogachev2007 p.129] 1.12.129, [@Dudley2002 p.102] 3.2.2-3．]

* $\mu$-零集合の全体を
$$
\cN(\mu):=\Brace{N\in P(X)\mid \mu^*(N)=0}
$$
で表し，$\mu$-零集合の補集合を **$\mu$-充満集合** と呼ぶ．^[full set の和訳として選んだ． [@Bogachev2007 p.110] では a set of full measure と表現している．$\cN(\mu)$ の記法は [@Dudley2002 p.101] に倣った．]

* $\mu$-零集合と $\mu$-充満集合との全体がなす $\sigma$-代数を $2:=\sigma(\cN(\mu))$ で表す．^[[@伊藤清1991 p.137] に従った．]

* $\mu$-可測集合 $A\in\cA_\mu$ に関して， 
$$
\cA_\mu\cap A:=\Brace{B\cap A\in\cA_\mu\mid B\in\cA_\mu}
$$
上への $\mu$ の制限を，$\mu|_A:\cA_\mu\cap A\to[0,\infty]$ で表す．^[[@Bogachev2007 p.23] に倣った．[@Bogachev2007 p.56] 1.12(iv) では $\cA_A$ とも表し，trace $\sigma$-algebra とも呼ぶという．[@Dellacherie-Meyer1978] では $\mu|_A$ の定義域を $\cA|_A$ で表す．]

* 測度空間の族 $(E_i,\cE_i,\mu_i)$ について，積集合 $\prod_{i\in I}E_i$ 上の [**積 $\sigma$-加法族**](https://ja.wikipedia.org/wiki/%E7%A9%8D%E6%B8%AC%E5%BA%A6) を
$$
\bigotimes_{i\in I}\cE_i=\sigma\paren{[\bigcup_{i\in I}]\pr_i^*(\cE_i)}
$$
で表す．^[[@Bogachev2007 p.188], [@Lang1993 p.158] に従った．]

* この上の直積測度を $\bigotimes_{i\in I}\mu_i$ で表す．^[このような一般的な場合の定義は [@Bogachev2007 p.189] 参照．]

* $\abs{I}=n,\mu_i=\mu$ の場合は $\mu^{\otimes n}$ とも表す．

* 位相空間 $(X,\cO)$ 上の [**Borel $\sigma$-加法族**](https://ja.wikipedia.org/wiki/%E3%83%9C%E3%83%AC%E3%83%AB%E9%9B%86%E5%90%88) を
$$
\B(X):=\sigma(\cO)
$$
で表す．

* $(\R,\B(\R))$ の積空間 $\R^T$ 上の積 $\sigma$-加法族を $\cC$ で表す．$(\R^T,\cC)$ 上の標準Gauss測度を $\gamma$ で表す．^[[@Gine-Nickl2021 p.16], [@Bogachev2020 p.171] に倣った．]

* $\ell_n$ は $\R^n$ 上の [Lebesgue 測度](https://ja.wikipedia.org/wiki/%E3%83%AB%E3%83%99%E3%83%BC%E3%82%B0%E6%B8%AC%E5%BA%A6) を表す．^[[@Nualart2018 p.8] に倣った．[@Bogachev2007 p.26], [@Gerber+2019] などは $\lambda_d$ と表す．[@Jacob2001 p.xv] は $\lambda^{(n)}$ で表す．] $\gamma_n:=\rN(0,1)^{\otimes n}$ は [標準 Gauss 測度](https://en.wikipedia.org/wiki/Gaussian_measure) を表す．
