---
title: "測度"
bibliography: 
    - ../../assets/2023.bib
    - ../../assets/2024.bib
    - ../../assets/2025.bib
csl: ../../assets/apalike.csl
---

{{< include ../../assets/_preamble.qmd >}}


* **符号付き測度** とは，可算加法的な関数
$$\mu:\cE\to[-\infty,\infty]$$
であって，
$$\{\pm\infty\}\subset\Im(\mu)$$
が起こらないものをいう．この全体を $\S(E)$ で表す．
^[$\cS$ は [@Nihat-Jost17-InformationGeometry 第3.1節 p.121] の記法に倣った．[@Bogachev2007], [@Villani2009] などはこれに $M(E)$ を用いる．符号付測度の定義は [@Dunford-Schwartz1958 p.95] III.1.1, [@Dudley2002 p.178] 5.6，[@吉田耕作1991 p.383] 定義7.1, [@Halmos1950 p.118] に一致する．]

* 有界な符号付き測度の全体を
$$
\cS^1(E)=\Brace{\mu\in\S(E)\mid\norm{\mu}_\TV<\infty}
$$
で表す．
^[[@DelMoral04-FeynmanKacFormulae p.7] では $\cM(E)$ と表し，[@Lang1993 p.199] では $M^1$，[@Revuz1984] では $\mathrm{b}\cM(\cE)$，[@Dunford-Schwartz1958] では $ca(E,\cE)$ と表す．我々も，添字 ${}^1$ を全変動が有限であることの象徴として採用する．実際，$\mu$-連続な測度 $\nu$ について，$\norm{\nu}_\TV=\Norm{\dd{\nu}{\mu}}_1$ である [@Lang1993 p.200] 定理3.3．有界かつRadonな符号付き測度を [@Pedersen1989 p.252] 6.5.8 は $M(E)$ と表す．実は有限次元 Banach 空間 $B$ について，$B$-値であることと有界であることは同値になる：[「有界」測度と「有限」測度](https://162348.github.io/posts/2023/FunctionalAnalysis/BoundedMeasure.html#sec-3) を参照．$\cS(E;B)$ の表記は，有界性はひとまず不問として $B$-値測度を表す際に使うこととする．全変動ノルムの記法は [@Gine-Nickl2021 p.2], [@Villani2009] に一致する．[@Bogachev2007] は $\norm{-}$ で表す．]

* **測度** の全体を $\cM(E):=\S(E)_+$ で表す．^[[@DelMoral-Penev2014 p.xli], [@DelMoral04-FeynmanKacFormulae p.7] では $\cM(E)$ を有界な符号付き測度に用いている．[@Jacob2001 p.xv] では $\cM^+(E)$ を測度の全体としている．] 有界な測度の全体を $\cM^1(E):=\cS^1(E)_+$ で表す．

* $S^1(E),M^1(E)$ などとイタリック体を用いた場合，$\cS^1(E),\cM^1(E)$ のうち Radon 測度のなす部分空間を表す．^[[@Bogachev2007 p.76] では $\cM_r(E)$ で表す．[@Dellacherie-Meyer1978] では，有界な Radon 測度の全体を $\cM_b^+(E)$ で表す．]

* $E$ を位相空間とする．有界な符号付き Borel 測度の列 $\{\mu_i\}\subset\cS^1(E,\B(E))$ の [弱収束](https://ja.wikipedia.org/wiki/確率変数の収束#分布収束) を，$\mu_i\Rightarrow\mu$ とも表す．^[[@Bogachev2007 p.175] 定義8.1.1 に倣った．]

* この弱位相に関する [ペアリング](https://ja.wikipedia.org/wiki/線型位相空間#弱位相) $(-|-):\cS^1(E,\B(E))\times C_b(E)\to\R$ を
$$
(\mu|f):=\int_Ef(x)\mu(dx)
$$
または単に $\mu f$ で表す．^[[@Crisan-Doucet2002] に一致する．[@Dellacherie-Meyer1978] は $\mu(f),\brac{\mu,f}$ のいずれも用いるとしている．]
