---
title: "確率核"
bibliography: 
    - ../../assets/2023.bib
    - ../../assets/2024.bib
    - ../../assets/2025.bib
csl: ../../assets/apalike.csl
---

{{< include ../../assets/_preamble.qmd >}}



[確率核](https://en.wikipedia.org/wiki/Markov_kernel) は可測空間の射となる基本的な対象である．$(E,\cE),(F,\F)$ を可測空間とする．

* [**核**](https://en.wikipedia.org/wiki/Transition_kernel) $T:E\to F$ とは，次の2条件を満たす写像 $T:E\times\F\to[0,\infty]$ をいう：^[[@Revuz-Yor1999 p.79] 定義III.1.1.1，[@Revuz1984 p.8] 定義1.1.1.1，[@Kallenberg2017 p.16], [@Bass2011 p.154] 定義19.2, [@Cho-Jacobs2019 p.962] 例7.2 では kernel，[@Jacod-Shiryaev2003 p.65]，[@Kolokoltsov2011-Generators p.110] 3.5節, [@Klenke2020 p.204] 8.3節 では transition kernel と呼んでいる．]
  * $\{T(x,-)\}_{x\in E}\subset\cM(F)$．
  * $\{T(-,A)\}_{A\in\F}\subset\cL(E)$．

* 核 $T:E\times\F\to[0,\infty]$ が **有界** であるとは，
$$
\sup_{x\in E}\abs{P(x,F)}<\infty
$$
を満たすことをいう．^[[@Kolokoltsov2011-Generators p.110] 3.5節 に倣った．[@DelMoral04-FeynmanKacFormulae p.9] は (bounded) integral operator と呼ぶ．] すなわち，写像 $E\to M^1(F)$ が有界な像を持つことをいう．^[実は有界核は，可測写像 $E\to M^1(F)$ と同一視出来る [@Kallenberg2017 p.30] 補題1.14．ただし，$M^1(F)$ には $\cL_b(F)$ が生成する最小の $\sigma$-代数を考える．]

* $\{P(x,F)\}_{x\in E}=\{1\}$ を満たす有界核 $P$ を **確率核** または [**Markov核**](https://en.wikipedia.org/wiki/Markov_kernel) という．
^[[@Crisan-Doucet2002 p.737] では Markov transition kernel，[@DelMoral04-FeynmanKacFormulae p.9], [@Ghosal-vanderVaart17-NonparametricBayes p.6], [@Fritz2020] では Markov kernel，[@Kolokoltsov2011-Generators p.110] 3.5節 では transition probability kernel or simply probability kernel と呼び，[@Chopin-Papaspiliopoulos20-SMC p.36] 定義4.1, [@Bremaud20-Processes p.135] 3.3.3節 では propability kernel，[@Kulik2018 p.25] では probability kernel としてさらに半群性も満たす族を transition probability kernels と呼ぶ．[@LeGall2016 pp.151-152] は Markovian transition kernel と transition semigroup と呼ぶ．[@Dellacherie-Meyer1988 p.2] は Markovian kernel．[@Kallenberg2017 p.29] と [@Hairer2021-Convergence] では可測関数 $E\to\cP(F)$ と定義しており，transition kernel と呼んでしまう．[@Bertsekas-Shreve1996 p.134] 定義7.12 は stochastic kernel，[@Giry1982], [@Neveu1970] は transition probability, [@Lawvere1962] は probabilistic mapping と呼んでいた．]

* $F$ が 可分距離空間上の確率空間であるとき，確率核 $P:E\to F$ とは可測写像 $T:E\to\cP(F)$ に等価である．ただし，$\cP(F)$ は弱収束の位相による Borel 可測空間と考える．^[[@Ghosal-vanderVaart17-NonparametricBayes p.510]，[@Kallenberg2017] 補題1.14 p.30，[@Hairer2021-Convergence], [@Ambrosio+2008 p.121]．この事実により，$E$ 上の（局所有限な） [ランダム測度](https://en.wikipedia.org/wiki/Random_measure) とは，確率空間からの核 $\Om\to E$ に等しい [@Kolokoltsov2010]．]

* 核 $T$ の符号付き測度の空間 $\cS(E)$ への右作用 $\cdot T:\cS(E)\to\cS(F)$ を
$$
\begin{align*}
    &(\mu T)(A)\\
    &\qquad:=\int_E\mu(dx)T(x,A),\\
    &\qquad\qquad(A\in\F),
\end{align*}
$$
で定める．

* 核 $T$ の可測関数の空間 $\L(F)$ への左作用 $T\cdot:\L(F)\to\L(E)$ を
$$
\begin{align*}
    &(Tf)(x)\\
    &\qquad:=\int_FT(x,dy)f(y),\\
    &\qquad\qquad (x\in E),
\end{align*}
$$
で定める．^[これにより，積分核も核であり，一般的に [積分核](https://en.wikipedia.org/wiki/Integral_transform) [@Conway2007 p.29] または 核関数 [@Scholkopf-Smola2002] などといったときは $T$ が $F$ 上で密度を持つ特別な場合であったことがわかる．[nLab](https://ncatlab.org/nlab/show/conditional+expectation#integral_kernel_stochastic_kernel) も参照．]

* 核 $T:E\to F,S:F\to G$ の **合成** $T\otimes S:E\to F\times G$ を
$$
\begin{align*}
    &(T\otimes S)(x,A\times B)\\
    &\qquad:=\int_AT(x,dy)S(y,B),\\
    &\qquad\qquad(x\in E,A\in\F,B\in\cG),
\end{align*}
$$
で定める．^[[@Kallenberg2017 p.16] の呼び方に従った．[@Gikhman-Skorokhod2004I p.79] では **直積** と呼ばれており，p.76 定理II.4.1 でその存在が示されている．[@Heng+2024] では $T=\mu$ という定値核の場合も同様の記法 $\mu\otimes S$ を定義している．]

* 核 $T:E\to F,S:F\to G$ の **積** $TS:E\to G$ を
$$
\begin{align*}
    (TS)(x,B)&:=(T\otimes S)(x,F\times B)\\
    &=\int_FT(x,dy)S(y,B)\\
    &\qquad(x\in E,B\in\cG),
\end{align*}
$$
で定める．^[こちらも，行列積の一般化であることを踏まえて [@Kallenberg2017 p.16] の呼び方に従った．[@Gikhman-Skorokhod2004I p.79] では **畳み込み** と呼ばれている．この式は [Chapman-Kolmogorov 方程式](https://en.wikipedia.org/wiki/Chapman%E2%80%93Kolmogorov_equation) と呼ばれるものである．そこで，Chapman-Kolmogorov 方程式は，Markov 核の族 $\{P_t\}_{t\in\R_+}$ が，この積という演算について半群性を満たす，という形の条件でよく登場する．]

::: {.callout-caution title="確率核の概念" icon="false" collapse="true"}

確率核は積に関して結合的で，$I(x,A):=\delta_x(A)$ を単位元に持ち，[可測空間と確率核の圏](https://en.wikipedia.org/wiki/Markov_kernel#Composition_of_Markov_Kernels_and_the_Markov_Category) $\Stoch$ をなす．これは $(1,2)$ を [終対象](https://ja.wikipedia.org/wiki/%E5%A7%8B%E5%AF%BE%E8%B1%A1%E3%81%A8%E7%B5%82%E5%AF%BE%E8%B1%A1) とする [Markov 圏](https://162348.github.io/posts/2023/Probability/MarkovCategory.html#sec-Stoch) である．

可測空間 $(1,2)$ からの確率核 $(1,2)\to(E,\cE)$ は $\cP(E)$ の元に等価である．^[これより，確率核 $T:E\to F$ は，確率測度 $(1,2)\to(E,\cE)$ を $(1,2)\to(F,\F)$ に「遷移」させているようにも思えるのである．]

グラフィカルモデルは，圏 $\Stoch$ における図式として理解できる．この立場から本ブログでは階層モデルや生成モデルを確率核 $\cZ\to\cX$ でも表す．

:::