---
title: "関数空間"
bibliography: 
    - ../../assets/2023.bib
    - ../../assets/2024.bib
    - ../../assets/2025.bib
csl: ../../assets/apalike.csl
---

{{< include ../../assets/_preamble.qmd >}}



$\F(E)\subset\R^E$ は $L(E), C(E)$ などの関数空間の一般形とし，$X,Y$ をノルム空間とする．

* 測度空間 $(E,\cE,\mu)$ 上の関数空間 $\F(E)$ に対して，文脈により $\F(\mu)$ とも $\F(E,\cE,\mu)$ とも表す．

* 任意の関数空間 $\F(E)$ に対して，値域の空間が $\X$ であるとき，これを強調して $\F(E;\X)$ または $\F_\X(E)$ とも表す．省略する場合は $\X=\R$ の場合に限る．^[$\F_\X(E)$ という表記は [@Ethier-Kurtz1986 p.95] に倣った．]

* 任意の関数空間 $\F(E)$ に対して，
  * 有界なもののなす部分空間を $\F_b(E)$ で表す．
  * コンパクト台を持つもののなす部分空間を $\F_c(E)$ で表す．^[[@Jacob2001] などは，コンパクト台を持つ連続関数の空間に $C_0(E)$ を用いる．]
  * 有界かつ一様連続なもののなす部分空間を $\F_u(E)$ で表す．^[[@Gine-Nickl2021 p.17], [@Jacob2001] に倣った．]
  * 高々多項式増大なもののなす部分空間を $\F_p(E)$ で表す．^[[@Nualart2018 p.1] に倣った．]
  * 非負値のもののなす錐を $\F(E)_+:=\F(E;\R_+)$ で表す．^[[@Pedersen1989 p.222] と [@Revuz1984] に倣った．[@Dellacherie-Meyer1978] は $\F(E)^+$ で表す．]
  * 正値なもののなす部分集合を $\F(E)^+:=\F(E;\R^+)$ で表す．^[このような使い分けは [@Nummelin1984 p.1] に一致する．]






* [**作用素**](https://ja.wikipedia.org/wiki/%E4%BD%9C%E7%94%A8%E7%B4%A0) $T:X\to Y$ と言ったとき，線型写像 $T:X\to Y$ を指すこととする．^[[@Helemskii2006 p.3] に一致する．]

* **$X$ 内の作用素** $T:X\supset\D(T)\to Y$ と言ったとき，ある $X$ の部分空間 $\D(T)$ 上で定義された作用素 $T:\D(T)\to Y$ を指すこととする．^[[@藤田+1991 p.103] などとは態度が違う．]

* 有界作用素の全体を $B(X,Y)$ で表す．^[[@Pedersen1989 p.44], [@Jacob2001 p.xvii] に倣った．[@藤田+1991 p.106] では $\L(X,Y)$ と表す．] $B(X):=B(X,X)$ とする．

* 連続作用素の全体を $L(X,Y)$ で表す．^[[@Lang1993 p.65], [@吉田耕作1995 p.110] に倣った．]

